name: demo_alarm_pg
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
    
  
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  permission_handler: ^11.3.1
  flutter_timezone: ^4.1.0
  alarm2: ^3.1.53

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/alarm.mp3
